# Generated by Django 3.2.9 on 2023-03-24 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booktitle', models.CharField(max_length=100)),
                ('authors', models.CharField(blank=True, max_length=200)),
                ('edition', models.CharField(blank=True, max_length=100)),
                ('booktype', models.CharField(blank=True, max_length=20)),
                ('deptclass', models.CharField(blank=True, max_length=100)),
                ('year', models.DateField()),
                ('isbn', models.CharField(blank=True, max_length=100)),
                ('aisle', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('dateadded', models.CharField(blank=True, max_length=100)),
                ('pdf_available', models.BooleanField()),
                ('pdf_file', models.FileField(upload_to='elibrary/pdfs/')),
            ],
        ),
    ]
