# Generated by Django 3.2.9 on 2023-03-24 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryhelper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='dateadded',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
