# Generated by Django 3.2.9 on 2023-03-24 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libraryhelper', '0002_alter_book_dateadded'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100)),
                ('matric', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=100)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryhelper.book')),
            ],
        ),
        migrations.CreateModel(
            name='Copy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copyname', models.CharField(max_length=100)),
                ('available', models.BooleanField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryhelper.book')),
            ],
        ),
    ]
