# Generated by Django 3.2.9 on 2023-03-24 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryhelper', '0003_copy_reservee'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='approve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='copy',
            name='approve',
            field=models.BooleanField(default=False),
        ),
    ]
