# Generated by Django 3.2.9 on 2023-03-24 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryhelper', '0004_auto_20230324_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pdf_file',
            field=models.FileField(blank=True, upload_to='elibrary/pdfs/'),
        ),
    ]
