# Generated by Django 3.2.9 on 2023-03-24 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryhelper', '0005_alter_book_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='booktitle',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='copy',
            name='copyname',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='reservee',
            name='matric',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
