# Generated by Django 3.2.9 on 2023-03-25 18:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('libraryhelper', '0007_alter_book_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservee',
            name='datecreated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
