# Generated by Django 3.2.9 on 2023-03-25 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryhelper', '0010_loan_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='returndate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
