# Generated by Django 3.2.9 on 2023-03-26 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libraryhelper', '0011_alter_loan_returndate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Defaulters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matric', models.CharField(max_length=100, unique=True)),
                ('prior', models.IntegerField()),
                ('firstname', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=100)),
                ('copy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryhelper.copy')),
            ],
        ),
    ]
