# Generated by Django 3.2.9 on 2023-03-30 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('libraryhelper', '0012_defaulters'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liberian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.TextField(max_length=200)),
                ('nin', models.TextField(max_length=200)),
                ('isAdmin', models.BooleanField()),
                ('profileimg', models.ImageField(upload_to='libraryhelper/images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
