# Generated by Django 3.2.9 on 2023-03-31 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryhelper', '0014_auto_20230330_2142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='liberian',
            old_name='Address',
            new_name='address',
        ),
        migrations.AddField(
            model_name='book',
            name='bookimg',
            field=models.ImageField(default='./blank-profile-picture-circle-hd.png', upload_to='elibrary/bookimages'),
        ),
        migrations.AddField(
            model_name='liberian',
            name='dob',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
