# Generated by Django 3.2.9 on 2023-03-31 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryhelper', '0015_auto_20230331_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bookimg',
            field=models.ImageField(default='./kraft-notebook-with-elastic-band-2542530__340.jpg', upload_to='elibrary/bookimages'),
        ),
    ]
