# Generated by Django 3.2.9 on 2023-03-31 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryhelper', '0016_alter_book_bookimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pdf_available',
            field=models.BooleanField(default=False),
        ),
    ]
