# Generated by Django 3.2.9 on 2023-03-31 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryhelper', '0018_alter_book_pdf_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='approve',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='copy',
            name='approve',
            field=models.BooleanField(default=True),
        ),
    ]
