# Generated by Django 3.2.9 on 2023-04-01 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryhelper', '0021_auto_20230331_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='approve',
            field=models.BooleanField(default=False),
        ),
    ]
