# Generated by Django 3.2.9 on 2023-04-01 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryhelper', '0023_auto_20230401_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liberian',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=2),
        ),
    ]
