# Generated by Django 3.2.9 on 2023-04-01 15:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryhelper', '0027_alter_liberian_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liberian',
            name='dob',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 1, 15, 38, 26, 408090)),
            preserve_default=False,
        ),
    ]
