# Generated by Django 3.2.9 on 2023-04-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryhelper', '0028_alter_liberian_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liberian',
            name='address',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='liberian',
            name='bio',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='liberian',
            name='dob',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='liberian',
            name='isAdmin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='liberian',
            name='nin',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
