# Generated by Django 3.2.9 on 2023-04-01 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryhelper', '0030_alter_liberian_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liberian',
            name='dob',
            field=models.DateField(blank=True),
        ),
    ]
