# Generated by Django 3.2.9 on 2023-04-08 03:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('libraryhelper', '0032_alter_liberian_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='popular',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='defaulters',
            name='datereated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
