# Generated by Django 3.2.9 on 2023-04-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryhelper', '0033_auto_20230408_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='booktitle',
            field=models.CharField(max_length=100),
        ),
    ]
