# Generated by Django 3.2.9 on 2023-04-22 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryhelper', '0034_alter_book_booktitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservee',
            name='matric',
            field=models.CharField(max_length=100),
        ),
    ]
