# Generated by Django 3.2.9 on 2023-04-30 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryhelper', '0036_loan_expectedreturndate'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='overlappeddate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
