# Generated by Django 3.2.9 on 2023-05-05 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryhelper', '0038_alter_book_popular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='popular',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
