# Generated by Django 3.2.9 on 2023-05-06 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryhelper', '0040_auto_20230505_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='dateloaned',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='expectedreturndate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='overlappeddate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='returndate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
