# Generated by Django 3.2.9 on 2023-05-06 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryhelper', '0041_auto_20230506_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='dateloaned',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='expectedreturndate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='overlappeddate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='returndate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
