# Generated by Django 3.2.9 on 2023-05-07 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryhelper', '0042_auto_20230506_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='overlappeddate',
            field=models.IntegerField(blank=True, default=4),
            preserve_default=False,
        ),
    ]
