# Generated by Django 3.2.19 on 2023-06-06 08:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryhelper', '0043_alter_loan_overlappeddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='expectedreturndate',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 6, 8, 50, 56, 950055), verbose_name=datetime.datetime(2023, 6, 13, 8, 50, 31, 113510)),
            preserve_default=False,
        ),
    ]
